modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "cheesy_slot" #mandatory
version = "${version}" #mandatory
displayName = "Cheesy Slot" #mandatory
logoFile = "icon.png" #optional
authors = "SJKZ1" #optional
description = '''
This mod show what key that set for selecting slot for some people forgot what they have set.
'''
[[dependencies.cheesy_slot]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.cheesy_slot]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.2.88,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cheesy_slot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
