modLoader = "javafml" #mandatory
loaderVersion = "[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "show_keybinds" #mandatory
version = "${version}" #mandatory
displayName = "Minecraft Show keybinds" #mandatory
logoFile = "icon.png" #optional
authors = "SJKZ1" #optional
description = '''
This mod show what key that set for selecting slot for some people forgot what they have set.
'''
[[dependencies.show_keybinds]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[44,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.show_keybinds]]
modId = "cloth_config"
mandatory = true
versionRange = "[9.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.show_keybinds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"
